import {ChangeDetectorRef,Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {forkJoin} from 'rxjs';import {parseCSV} from '../../utils/csv-parser';import {BusService} from '../../service/bus.service';import {TypeBusService} from '../../service/type-bus.service';import {Bus as BusModel,BusRequest,TypeBus} from '../../service/api.models';
type BusView=BusModel&{numero:string;assignation:string;statut:string};
@Component({selector:'app-bus',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./bus.html',styleUrl:'./bus.css'})export class Bus implements OnInit{
 afficherFormulaire=false;modeModification=false;busSelectionne?:BusView;afficherImport=false;isDragging=false;messageImport='';typeMessageImport='';messageFormulaire='';successMessage='';numero='';typeBusId:number|null=null;recherche='';statut='Actif';bus:BusView[]=[];typesBus:TypeBus[]=[];
 constructor(private api:BusService,private typesApi:TypeBusService,private cdr:ChangeDetectorRef){}ngOnInit(){this.charger()}
 private charger(){forkJoin({bus:this.api.getAll(),types:this.typesApi.getAll()}).subscribe({next:x=>{this.typesBus=x.types;this.bus=x.bus.map(b=>({...b,numero:b.numeroBus,assignation:b.typeBusLibelle,statut:b.actif?'Actif':'Inactif'}));this.cdr.detectChanges()},error:e=>{this.afficherErreur(e,'Impossible de contacter le serveur.');this.cdr.detectChanges()}})}
 get busFiltres(){const q=this.recherche.toLowerCase();return this.bus.filter(b=>b.numeroBus.toLowerCase().includes(q)||b.typeBusLibelle.toLowerCase().includes(q))}ajouterBus(){this.afficherFormulaire=true;this.modeModification=false;this.busSelectionne=undefined;this.numero='';this.typeBusId=null;this.statut='Actif';this.messageFormulaire='';this.successMessage=''}
 enregistrerBus(){if(!this.numero.trim()||this.typeBusId===null){this.messageFormulaire='Numéro du bus et type du bus obligatoires.';return}const p:BusRequest={numeroBus:this.numero.trim(),typeBusId:Number(this.typeBusId),actif:this.statut!=='Inactif'};const editing=this.modeModification&&this.busSelectionne;const r=editing?this.api.update(this.busSelectionne!.id,p):this.api.create(p);r.subscribe({next:()=>{this.successMessage=editing?'Bus modifié avec succès.':'Bus ajouté avec succès.';this.afficherFormulaire=false;this.modeModification=false;this.charger()},error:e=>this.afficherErreur(e,'Enregistrement impossible.')})}
 modifierBus(b:BusView){this.busSelectionne=b;this.numero=b.numeroBus;this.typeBusId=b.typeBusId;this.statut=b.actif?'Actif':'Inactif';this.afficherFormulaire=true;this.modeModification=true;this.messageFormulaire=''}supprimerBus(id:number){this.api.delete(id).subscribe({next:()=>this.charger(),error:e=>this.afficherErreur(e,'La désactivation a échoué.')})}
 basculerImport(){this.afficherImport=!this.afficherImport;this.messageImport=''}onDragOver(e:DragEvent){e.preventDefault();this.isDragging=true}onDragLeave(e:DragEvent){e.preventDefault();this.isDragging=false}onDrop(e:DragEvent){e.preventDefault();this.isDragging=false;const f=e.dataTransfer?.files[0];if(f)this.lireFichier(f)}onFileSelected(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)this.lireFichier(f)}private lireFichier(f:File){const r=new FileReader();r.onload=e=>this.traiterCSV(String(e.target?.result??''));r.readAsText(f)}
 private traiterCSV(c:string){const calls=parseCSV(c).flatMap(row=>{const type=this.typesBus.find(t=>t.libelle.toLowerCase()===String(row.typeBus??row.assignation??'').toLowerCase());return type?[this.api.create({numeroBus:String(row.numeroBus??row.numero??'').trim(),typeBusId:type.id,actif:String(row.statut??'Actif').toLowerCase()!=='inactif'})]:[]});if(!calls.length){this.messageImport='Aucune ligne CSV valide.';this.typeMessageImport='error';return}forkJoin(calls).subscribe({next:()=>{this.messageImport=`${calls.length} bus importé(s).`;this.typeMessageImport='success';this.charger()},error:e=>this.afficherErreur(e,"L'import a échoué.")})}private afficherErreur(e:any,f:string){console.error(e);this.messageFormulaire=e?.error?.message||e?.message||f;this.messageImport=this.messageFormulaire;this.typeMessageImport='error'}}
