package com.alsa.alsacleanfleet.service;
import com.alsa.alsacleanfleet.dto.*;import com.alsa.alsacleanfleet.entity.Utilisateur;import com.alsa.alsacleanfleet.exception.*;import com.alsa.alsacleanfleet.repository.UtilisateurRepository;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service @Transactional public class UtilisateurService {private final UtilisateurRepository repo;private final PasswordEncoder encoder;public UtilisateurService(UtilisateurRepository r,PasswordEncoder encoder){repo=r;this.encoder=encoder;}
 @Transactional(readOnly=true) public List<UtilisateurResponseDTO> findAll(){return repo.findAll().stream().map(this::dto).toList();} @Transactional(readOnly=true) public UtilisateurResponseDTO findById(Long id){return dto(entity(id));}
 public UtilisateurResponseDTO create(UtilisateurRequestDTO d){if(d.motDePasse()==null||d.motDePasse().isBlank())throw new BusinessException("Le mot de passe est obligatoire");check(d,-1L);Utilisateur u=new Utilisateur();apply(u,d,true);return dto(repo.save(u));}
 public UtilisateurResponseDTO update(Long id,UtilisateurRequestDTO d){Utilisateur u=entity(id);check(d,id);apply(u,d,false);return dto(repo.save(u));} public void delete(Long id){Utilisateur u=entity(id);u.setActif(false);repo.save(u);}
 private Utilisateur entity(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Utilisateur introuvable"));} private void check(UtilisateurRequestDTO d,Long id){if(repo.existsByLoginIgnoreCaseAndIdNot(d.login().trim(),id))throw new DuplicateResourceException("Ce login est déjà utilisé");if(repo.existsByEmailIgnoreCaseAndIdNot(d.email().trim(),id))throw new DuplicateResourceException("Cet email est déjà utilisé");if(repo.existsByMatriculeIgnoreCaseAndIdNot(d.matricule().trim(),id))throw new DuplicateResourceException("Ce matricule est déjà utilisé");}
 private void apply(Utilisateur u,UtilisateurRequestDTO d,boolean creating){u.setNom(d.nom().trim());u.setPrenom(d.prenom().trim());u.setMatricule(d.matricule().trim());u.setTelephone(d.telephone());u.setEmail(d.email().trim());u.setLogin(d.login().trim());if(d.motDePasse()!=null&&!d.motDePasse().isBlank())u.setMotDePasse(encoder.encode(d.motDePasse()));u.setRole(d.role());u.setActif(d.actif()==null||d.actif());if(creating)u.setDoitChangerMotDePasse(d.role()!=com.alsa.alsacleanfleet.enums.Role.ADMINISTRATEUR);}
 private UtilisateurResponseDTO dto(Utilisateur u){return new UtilisateurResponseDTO(u.getId(),u.getNom(),u.getPrenom(),u.getMatricule(),u.getTelephone(),u.getEmail(),u.getLogin(),u.getRole(),u.getActif());}}
