import {DOCUMENT,isPlatformBrowser} from '@angular/common';
import {Inject,Injectable,PLATFORM_ID} from '@angular/core';

export type AppLanguage='fr'|'en'|'ar'|'es';
type Translation={en:string;ar:string};

const T:Record<string,Translation>={
  'Système de gestion de flotte':{en:'Fleet management system',ar:'نظام إدارة الأسطول'},'Menu principal':{en:'Main menu',ar:'القائمة الرئيسية'},
  'Tableau de bord':{en:'Dashboard',ar:'لوحة التحكم'},'Utilisateurs':{en:'Users',ar:'المستخدمون'},'Nettoyages':{en:'Cleanings',ar:'عمليات التنظيف'},'Rapports':{en:'Reports',ar:'التقارير'},'Paramètres':{en:'Settings',ar:'الإعدادات'},
  'Recherche rapide...':{en:'Quick search...',ar:'بحث سريع...'},'Notifications':{en:'Notifications',ar:'الإشعارات'},'Administrateur':{en:'Administrator',ar:'المسؤول'},'Mon profil':{en:'My profile',ar:'ملفي الشخصي'},'Déconnexion':{en:'Log out',ar:'تسجيل الخروج'},
  'Bienvenue, Administrateur 👋':{en:'Welcome, Administrator 👋',ar:'مرحباً، أيها المسؤول 👋'},'Gérez les bus, les utilisateurs et les opérations de nettoyage depuis votre tableau de bord.':{en:'Manage buses, users and cleaning operations from your dashboard.',ar:'قم بإدارة الحافلات والمستخدمين وعمليات التنظيف من لوحة التحكم.'},
  'Chargement des données…':{en:'Loading data…',ar:'جارٍ تحميل البيانات…'},'Chargement…':{en:'Loading…',ar:'جارٍ التحميل…'},'Total Bus':{en:'Total buses',ar:'إجمالي الحافلات'},'+3 ce mois':{en:'+3 this month',ar:'+3 هذا الشهر'},
  'Nettoyages du jour':{en:"Today's cleanings",ar:'عمليات تنظيف اليوم'},'Nettoyages validés':{en:'Approved cleanings',ar:'عمليات التنظيف المعتمدة'},'Nettoyages refusés':{en:'Rejected cleanings',ar:'عمليات التنظيف المرفوضة'},'Nettoyages en attente':{en:'Pending cleanings',ar:'عمليات التنظيف قيد الانتظار'},'Pourcentage validation':{en:'Approval percentage',ar:'نسبة الاعتماد'},
  'Liste des Bus':{en:'Bus list',ar:'قائمة الحافلات'},'Gérez et importez votre flotte de bus':{en:'Manage and import your bus fleet',ar:'إدارة واستيراد أسطول الحافلات'},'Rechercher un bus…':{en:'Search for a bus…',ar:'البحث عن حافلة…'},'Importer CSV':{en:'Import CSV',ar:'استيراد CSV'},'Ajouter un bus':{en:'Add a bus',ar:'إضافة حافلة'},'Numéro du bus':{en:'Bus number',ar:'رقم الحافلة'},'Sélectionner un type de bus':{en:'Select a bus type',ar:'اختر نوع الحافلة'},'Type de bus':{en:'Bus type',ar:'نوع الحافلة'},'Flotte de bus':{en:'Bus fleet',ar:'أسطول الحافلات'},'Numéro de bus':{en:'Bus number',ar:'رقم الحافلة'},'Aucun bus trouvé':{en:'No bus found',ar:'لم يتم العثور على حافلات'},
  'Actif':{en:'Active',ar:'نشط'},'Inactif':{en:'Inactive',ar:'غير نشط'},'Gérez les comptes et les rôles des utilisateurs':{en:'Manage user accounts and roles',ar:'إدارة حسابات المستخدمين وأدوارهم'},'Rechercher un utilisateur…':{en:'Search for a user…',ar:'البحث عن مستخدم…'},'Ajouter un utilisateur':{en:'Add a user',ar:'إضافة مستخدم'},
  'Nom':{en:'Last name',ar:'الاسم العائلي'},'Prénom':{en:'First name',ar:'الاسم الشخصي'},'Nom Complet':{en:'Full name',ar:'الاسم الكامل'},'Nom complet':{en:'Full name',ar:'الاسم الكامل'},'Matricule':{en:'Employee ID',ar:'الرقم الوظيفي'},'Téléphone':{en:'Phone',ar:'الهاتف'},'Mot de passe':{en:'Password',ar:'كلمة المرور'},'Rôle':{en:'Role',ar:'الدور'},'Aucun utilisateur trouvé':{en:'No user found',ar:'لم يتم العثور على مستخدمين'},
  'Nettoyeur':{en:'Cleaner',ar:'عامل النظافة'},'Superviseur':{en:'Supervisor',ar:'المشرف'},'Planifiez et suivez les opérations de nettoyage':{en:'Plan and track cleaning operations',ar:'تخطيط وتتبع عمليات التنظيف'},'Rechercher un nettoyage…':{en:'Search for a cleaning…',ar:'البحث عن عملية تنظيف…'},'Ajouter un nettoyage':{en:'Add a cleaning',ar:'إضافة عملية تنظيف'},'Choisir un bus':{en:'Choose a bus',ar:'اختر حافلة'},'Type de nettoyage':{en:'Cleaning type',ar:'نوع التنظيف'},'Choisir un nettoyeur':{en:'Choose a cleaner',ar:'اختر عامل النظافة'},'Aucun superviseur':{en:'No supervisor',ar:'بدون مشرف'},'Aucun nettoyage trouvé':{en:'No cleaning found',ar:'لم يتم العثور على عمليات تنظيف'},
  'En attente':{en:'Pending',ar:'قيد الانتظار'},'Validé':{en:'Approved',ar:'معتمد'},'Validés':{en:'Approved',ar:'معتمدة'},'Refusé':{en:'Rejected',ar:'مرفوض'},'Refusés':{en:'Rejected',ar:'مرفوضة'},'Statut':{en:'Status',ar:'الحالة'},'Actions':{en:'Actions',ar:'الإجراءات'},
  'Rapports & Analyses':{en:'Reports & Analytics',ar:'التقارير والتحليلات'},'Suivi des opérations de nettoyage des bus':{en:'Bus cleaning operation monitoring',ar:'متابعة عمليات تنظيف الحافلات'},'Export Excel':{en:'Export Excel',ar:'تصدير Excel'},'Export PDF':{en:'Export PDF',ar:'تصدير PDF'},'Aucune donnée':{en:'No data',ar:'لا توجد بيانات'},'Filtres':{en:'Filters',ar:'عوامل التصفية'},'Date début':{en:'Start date',ar:'تاريخ البداية'},'Date fin':{en:'End date',ar:'تاريخ النهاية'},'Tous':{en:'All',ar:'الكل'},'Filtrer':{en:'Filter',ar:'تصفية'},'Historique des nettoyages':{en:'Cleaning history',ar:'سجل عمليات التنظيف'},'Durée':{en:'Duration',ar:'المدة'},'Aucun rapport trouvé.':{en:'No report found.',ar:'لم يتم العثور على تقارير.'},
  "Configuration des paramètres de l'application":{en:'Application settings configuration',ar:'إعدادات التطبيق'},'Préférences':{en:'Preferences',ar:'التفضيلات'},'Gérer les préférences générales.':{en:'Manage general preferences.',ar:'إدارة التفضيلات العامة.'},'Langue':{en:'Language',ar:'اللغة'},'Français':{en:'French',ar:'الفرنسية'},'Arabe':{en:'Arabic',ar:'العربية'},'Activer les notifications':{en:'Enable notifications',ar:'تفعيل الإشعارات'},'Apparence':{en:'Appearance',ar:'المظهر'},"Personnaliser l'affichage de l'application.":{en:'Customize the application display.',ar:'تخصيص مظهر التطبيق.'},'Mode sombre':{en:'Dark mode',ar:'الوضع الداكن'},'Informations système':{en:'System information',ar:'معلومات النظام'},'Application':{en:'Application',ar:'التطبيق'},'Version':{en:'Version',ar:'الإصدار'},'Environnement':{en:'Environment',ar:'البيئة'},'Production':{en:'Production',ar:'الإنتاج'},
  'Ancien mot de passe':{en:'Current password',ar:'كلمة المرور الحالية'},'Nouveau mot de passe':{en:'New password',ar:'كلمة المرور الجديدة'},'Confirmer mot de passe':{en:'Confirm password',ar:'تأكيد كلمة المرور'}
};

const ES:Record<string,string>={
  'Fleet management system':'Sistema de gestión de flota','Main menu':'Menú principal','Dashboard':'Panel de control','Users':'Usuarios','Cleanings':'Limpiezas','Reports':'Informes','Settings':'Configuración',
  'Quick search...':'Búsqueda rápida...','Notifications':'Notificaciones','Administrator':'Administrador','My profile':'Mi perfil','Log out':'Cerrar sesión',
  'Welcome, Administrator 👋':'Bienvenido, Administrador 👋','Manage buses, users and cleaning operations from your dashboard.':'Gestione los autobuses, los usuarios y las operaciones de limpieza desde su panel de control.',
  'Loading data…':'Cargando datos…','Loading…':'Cargando…','Total buses':'Total de autobuses','+3 this month':'+3 este mes',"Today's cleanings":'Limpiezas de hoy','Approved cleanings':'Limpiezas aprobadas','Rejected cleanings':'Limpiezas rechazadas','Pending cleanings':'Limpiezas pendientes','Approval percentage':'Porcentaje de aprobación',
  'Bus list':'Lista de autobuses','Manage and import your bus fleet':'Gestione e importe su flota de autobuses','Search for a bus…':'Buscar un autobús…','Import CSV':'Importar CSV','Add a bus':'Añadir un autobús','Bus number':'Número de autobús','Select a bus type':'Seleccione un tipo de autobús','Bus type':'Tipo de autobús','Bus fleet':'Flota de autobuses','No bus found':'No se encontró ningún autobús',
  'Active':'Activo','Inactive':'Inactivo','Manage user accounts and roles':'Gestione las cuentas y funciones de los usuarios','Search for a user…':'Buscar un usuario…','Add a user':'Añadir un usuario','Last name':'Apellido','First name':'Nombre','Full name':'Nombre completo','Employee ID':'Matrícula','Phone':'Teléfono','Password':'Contraseña','Role':'Rol','No user found':'No se encontró ningún usuario',
  'Cleaner':'Limpiador','Supervisor':'Supervisor','Plan and track cleaning operations':'Planifique y supervise las operaciones de limpieza','Search for a cleaning…':'Buscar una limpieza…','Add a cleaning':'Añadir una limpieza','Choose a bus':'Elija un autobús','Cleaning type':'Tipo de limpieza','Choose a cleaner':'Elija un limpiador','No supervisor':'Sin supervisor','No cleaning found':'No se encontró ninguna limpieza',
  'Pending':'Pendiente','Approved':'Aprobado','Rejected':'Rechazado','Status':'Estado','Actions':'Acciones','Reports & Analytics':'Informes y análisis','Bus cleaning operation monitoring':'Seguimiento de las operaciones de limpieza de autobuses','Export Excel':'Exportar a Excel','Export PDF':'Exportar a PDF','No data':'Sin datos','Filters':'Filtros','Start date':'Fecha de inicio','End date':'Fecha de fin','All':'Todos','Filter':'Filtrar','Cleaning history':'Historial de limpiezas','Duration':'Duración','No report found.':'No se encontró ningún informe.',
  'Application settings configuration':'Configuración de la aplicación','Preferences':'Preferencias','Manage general preferences.':'Gestione las preferencias generales.','Language':'Idioma','French':'Francés','Arabic':'Árabe','Enable notifications':'Activar las notificaciones','Appearance':'Apariencia','Customize the application display.':'Personalice la apariencia de la aplicación.','Dark mode':'Modo oscuro','System information':'Información del sistema','Application':'Aplicación','Version':'Versión','Environment':'Entorno','Production':'Producción','Current password':'Contraseña actual','New password':'Nueva contraseña','Confirm password':'Confirmar contraseña'
};

@Injectable({providedIn:'root'})
export class LanguageService {
  private language:AppLanguage='fr'; private observer?:MutationObserver;
  private originals=new WeakMap<Node,string>(); private attributeOriginals=new WeakMap<Element,Map<string,string>>();
  constructor(@Inject(DOCUMENT) private document:Document,@Inject(PLATFORM_ID) platformId:object){if(!isPlatformBrowser(platformId))return;const saved=localStorage.getItem('app-language');if(saved==='fr'||saved==='en'||saved==='ar'||saved==='es')this.language=saved;queueMicrotask(()=>{this.apply();this.observe();});}
  get currentLanguage():AppLanguage{return this.language;}
  setLanguage(language:AppLanguage):void{this.language=language;localStorage.setItem('app-language',language);this.apply();}
  private observe():void{if(!this.document.body)return;this.observer=new MutationObserver(ms=>{this.observer?.disconnect();ms.forEach(m=>m.addedNodes.forEach(n=>this.translateTree(n)));this.observe();});this.observer.observe(this.document.body,{childList:true,subtree:true});}
  private apply():void{this.document.documentElement.lang=this.language;this.document.documentElement.dir=this.language==='ar'?'rtl':'ltr';if(this.document.body)this.translateTree(this.document.body);}
  private translateTree(root:Node):void{if(root.nodeType===Node.TEXT_NODE){this.translateNode(root);return;}if(!(root instanceof Element))return;this.translateAttributes(root);const walker=this.document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode()))this.translateNode(node);root.querySelectorAll('*').forEach(e=>this.translateAttributes(e));}
  private translateNode(node:Node):void{if(!this.originals.has(node))this.originals.set(node,node.textContent??'');const original=this.originals.get(node)??'';const clean=original.trim();const translated=this.getTranslation(clean);node.textContent=this.localizeDigits(translated?original.replace(clean,translated):original);}
  private translateAttributes(element:Element):void{for(const attribute of ['placeholder','title','aria-label']){const current=element.getAttribute(attribute);if(current===null)continue;let values=this.attributeOriginals.get(element);if(!values){values=new Map();this.attributeOriginals.set(element,values);}if(!values.has(attribute))values.set(attribute,current);const original=values.get(attribute)??current;element.setAttribute(attribute,this.localizeDigits(this.getTranslation(original)||original));}}
  private getTranslation(value:string):string{if(this.language==='fr')return value;const entry=T[value];if(entry)return this.translationFor(entry);const clean=value.replace(/^[^\p{L}\p{N}]+/u,'');const fallback=T[clean];return fallback?value.slice(0,value.length-clean.length)+this.translationFor(fallback):value;}
  private translationFor(entry:Translation):string{return this.language==='es'?(ES[entry.en]??entry.en):entry[this.language as 'en'|'ar'];}
  private localizeDigits(value:string):string{return this.language==='ar'?value.replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]):value;}
}
