import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {forkJoin} from 'rxjs';import {BusService} from '../../service/bus.service';import {NettoyageService} from '../../service/nettoyage.service';import {TypeNettoyageService} from '../../service/type-nettoyage.service';import {UtilisateurService} from '../../service/utilisateur.service';import {Bus,Nettoyage,NettoyageRequest,StatutNettoyage,TypeNettoyage,Utilisateur} from '../../service/api.models';
import {ChangeDetectorRef,inject} from '@angular/core';
type NettoyageView=Nettoyage&{busLabel:string;type:string;statutLabel:string};const labels:Record<StatutNettoyage,string>={EN_ATTENTE:'En attente',VALIDE:'Validé',REFUSE:'Refusé'};
@Component({selector:'app-nettoyages',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./nettoyages.html',styleUrl:'./nettoyages.css'})export class Nettoyages implements OnInit{
 private readonly cdr=inject(ChangeDetectorRef);
 afficherFormulaire=false;modeModification=false;nettoyageSelectionne?:NettoyageView;afficherImport=false;isDragging=false;messageImport='';typeMessageImport='';messageFormulaire='';recherche='';bus:Bus[]=[];typesNettoyage:TypeNettoyage[]=[];utilisateurs:Utilisateur[]=[];nettoyage:NettoyageView[]=[];form={busId:null as number|null,typeNettoyageId:null as number|null,nettoyeurId:null as number|null,superviseurId:null as number|null,dateNettoyage:'',statut:'EN_ATTENTE' as StatutNettoyage};
 constructor(private api:NettoyageService,private busApi:BusService,private typesApi:TypeNettoyageService,private usersApi:UtilisateurService){}ngOnInit(){this.charger()}get nettoyeurs(){return this.utilisateurs.filter(u=>u.role==='NETTOYEUR'&&u.actif)}get superviseurs(){return this.utilisateurs.filter(u=>(u.role==='SUPERVISEUR'||u.role==='ADMINISTRATEUR')&&u.actif)}get nettoyagesFiltres(){const q=this.recherche.toLowerCase();return this.nettoyage.filter(n=>`${n.busLabel} ${n.type} ${n.statutLabel}`.toLowerCase().includes(q))}
 private charger(){forkJoin({values:this.api.getAll(),bus:this.busApi.getAll(),types:this.typesApi.getAll(),users:this.usersApi.getUtilisateurs()}).subscribe({next:x=>{this.bus=x.bus.filter(b=>b.actif);this.typesNettoyage=x.types;this.utilisateurs=x.users;this.nettoyage=x.values.map(n=>({...n,busLabel:`Bus ${n.numeroBus}`,type:n.typeNettoyageLibelle,statutLabel:labels[n.statut]}));this.cdr.detectChanges()},error:e=>{this.erreur(e,'Impossible de charger les données du formulaire.');this.cdr.detectChanges()}})}
 ajouterNettoyage(){this.afficherFormulaire=true;this.modeModification=false;this.nettoyageSelectionne=undefined;this.form={busId:null,typeNettoyageId:null,nettoyeurId:null,superviseurId:null,dateNettoyage:new Date().toISOString().slice(0,10),statut:'EN_ATTENTE'};this.messageFormulaire=''}
 enregistrerNettoyage(){if(this.form.busId===null||this.form.typeNettoyageId===null||this.form.nettoyeurId===null||!this.form.dateNettoyage){this.messageFormulaire='Bus, type de nettoyage, nettoyeur et date sont obligatoires.';return;}const p:NettoyageRequest={busId:Number(this.form.busId),typeNettoyageId:Number(this.form.typeNettoyageId),nettoyeurId:Number(this.form.nettoyeurId),superviseurId:this.form.superviseurId===null?undefined:Number(this.form.superviseurId),dateNettoyage:this.form.dateNettoyage,statut:'EN_ATTENTE'};const editing=this.modeModification&&this.nettoyageSelectionne;const r=editing?this.api.update(this.nettoyageSelectionne!.id,p):this.api.create(p);r.subscribe({next:()=>{this.afficherFormulaire=false;this.charger()},error:e=>this.erreur(e,"L'enregistrement du nettoyage a échoué.")})}
 modifierNettoyage(n:NettoyageView){this.nettoyageSelectionne=n;this.form={busId:n.busId,typeNettoyageId:n.typeNettoyageId,nettoyeurId:n.nettoyeurId,superviseurId:n.superviseurId??null,dateNettoyage:n.dateNettoyage,statut:n.statut};this.afficherFormulaire=true;this.modeModification=true;this.messageFormulaire=''}supprimerNettoyage(id:number){this.api.delete(id).subscribe({next:()=>this.charger(),error:e=>this.erreur(e,'La suppression a échoué.')})}basculerImport(){this.afficherImport=!this.afficherImport;this.messageImport=''}onDragOver(e:DragEvent){e.preventDefault();this.isDragging=true}onDragLeave(e:DragEvent){e.preventDefault();this.isDragging=false}onDrop(e:DragEvent){e.preventDefault();this.isDragging=false}onFileSelected(e:Event){}private erreur(e:any,f:string){console.error(e);this.messageFormulaire=e?.error?.message||e?.message||f;this.messageImport=this.messageFormulaire;this.typeMessageImport='error'}}
