CREATE TABLE types_bus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(100) NOT NULL
);

CREATE TABLE types_nettoyage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT "UK70xxxq111ssvaajj7ynmwad44" UNIQUE (libelle)
);

CREATE TABLE utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    matricule VARCHAR(50) NOT NULL,
    telephone VARCHAR(255),
    email VARCHAR(150) NOT NULL,
    login VARCHAR(100) NOT NULL,
    mot_de_passe VARCHAR(255),
    role VARCHAR(15) NOT NULL,
    actif BOOLEAN DEFAULT TRUE,
    doit_changer_mot_de_passe BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT utilisateurs_role_check CHECK (
        role IN ('ADMINISTRATEUR', 'SUPERVISEUR', 'NETTOYEUR', 'CONSULTANT')
    ),
    CONSTRAINT matricule UNIQUE (matricule),
    CONSTRAINT email UNIQUE (email),
    CONSTRAINT login UNIQUE (login)
);

CREATE TABLE bus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_bus VARCHAR(50) NOT NULL,
    actif BOOLEAN DEFAULT TRUE,
    type_bus_id BIGINT,
    immatriculation VARCHAR(255),
    CONSTRAINT "UKloxwiism3a5yw9b7x35pm7mtk" UNIQUE (immatriculation),
    CONSTRAINT fk_bus_type FOREIGN KEY (type_bus_id)
        REFERENCES types_bus (id) ON DELETE SET NULL
);

CREATE INDEX fk_bus_type_idx ON bus (type_bus_id);

CREATE TABLE nettoyages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_id BIGINT,
    type_nettoyage_id BIGINT,
    nettoyeur_id BIGINT,
    superviseur_id BIGINT,
    date DATE,
    heure_debut TIMESTAMP WITHOUT TIME ZONE,
    heure_fin TIMESTAMP WITHOUT TIME ZONE,
    duree INTEGER,
    remarque_nettoyeur TEXT,
    remarque_superviseur TEXT,
    statut VARCHAR(10) NOT NULL,
    date_validation TIMESTAMP WITHOUT TIME ZONE,
    date_nettoyage DATE NOT NULL,
    CONSTRAINT nettoyages_statut_check CHECK (
        statut IN ('EN_ATTENTE', 'VALIDE', 'REFUSE')
    ),
    CONSTRAINT fk_nettoyage_bus FOREIGN KEY (bus_id)
        REFERENCES bus (id) ON DELETE SET NULL,
    CONSTRAINT fk_nettoyage_type FOREIGN KEY (type_nettoyage_id)
        REFERENCES types_nettoyage (id) ON DELETE SET NULL,
    CONSTRAINT fk_nettoyage_nettoyeur FOREIGN KEY (nettoyeur_id)
        REFERENCES utilisateurs (id) ON DELETE SET NULL,
    CONSTRAINT fk_nettoyage_superviseur FOREIGN KEY (superviseur_id)
        REFERENCES utilisateurs (id) ON DELETE SET NULL
);

CREATE INDEX fk_nettoyage_type ON nettoyages (type_nettoyage_id);
CREATE INDEX fk_nettoyage_superviseur ON nettoyages (superviseur_id);
CREATE INDEX idx_nettoyage_date ON nettoyages (date);
CREATE INDEX idx_nettoyage_statut ON nettoyages (statut);
CREATE INDEX idx_nettoyage_nettoyeur ON nettoyages (nettoyeur_id);
CREATE INDEX idx_nettoyage_bus ON nettoyages (bus_id);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinataire_id BIGINT NOT NULL,
    nettoyage_id BIGINT,
    message VARCHAR(500) NOT NULL,
    lue BOOLEAN NOT NULL DEFAULT FALSE,
    date_creation TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_notification_destinataire_date
    ON notifications (destinataire_id, date_creation);
CREATE INDEX idx_notification_non_lue
    ON notifications (destinataire_id, lue);
CREATE INDEX "FKp8a3gdmbeo7j241ko7lb4sq29"
    ON notifications (nettoyage_id);
