spring.application.name=alsa-clean-fleet
spring.datasource.url=jdbc:mysql://localhost:3306/alsa_clean_fleet
spring.datasource.username=root
spring.datasource.password=marwamarar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true