import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {forkJoin} from 'rxjs';import {parseCSV} from '../../utils/csv-parser';import {UtilisateurService} from '../../service/utilisateur.service';import {Role,Utilisateur,UtilisateurRequest} from '../../service/api.models';
import {ChangeDetectorRef,inject} from '@angular/core';
type UserView=Utilisateur&{roleLabel:string};const labels:Record<Role,string>={ADMINISTRATEUR:'Administrateur',NETTOYEUR:'Nettoyeur',SUPERVISEUR:'Superviseur'};
@Component({selector:'app-utilisateurs',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./utilisateurs.html',styleUrl:'./utilisateurs.css'})export class Utilisateurs implements OnInit{
 private readonly cdr=inject(ChangeDetectorRef);
 afficherFormulaire=false;modeModification=false;utilisateurSelectionne?:UserView;afficherImport=false;isDragging=false;messageImport='';typeMessageImport='';messageFormulaire='';successMessage='';nom='';prenom='';matricule='';telephone='';email='';login='';motDePasse='';role: Role | '' = '';recherche='';utilisateurs:UserView[]=[];
 constructor(private api:UtilisateurService){}ngOnInit(){this.charger()}private charger(){this.api.getUtilisateurs().subscribe({next:u=>{this.utilisateurs=u.map(x=>({...x,roleLabel:labels[x.role]}));this.cdr.detectChanges()},error:e=>{this.erreur(e,'Impossible de charger les utilisateurs.');this.cdr.detectChanges()}})}get utilisateursFiltres(){const q=this.recherche.toLowerCase();return this.utilisateurs.filter(u=>`${u.nom} ${u.prenom} ${u.email} ${u.matricule}`.toLowerCase().includes(q))}
 ajouterUtilisateur(){this.afficherFormulaire=true;this.modeModification=false;this.utilisateurSelectionne=undefined;this.nom=this.prenom=this.matricule=this.telephone=this.email=this.login=this.motDePasse='';this.role='';this.messageFormulaire='';}
 enregistrerUtilisateur(){if(!this.nom.trim()||!this.prenom.trim()||!this.matricule.trim()||!this.email.trim()||!this.login.trim()||!this.role||(!this.modeModification&&!this.motDePasse)){this.messageFormulaire='Nom, prénom, matricule, email, login, rôle et mot de passe sont obligatoires.';return;}const p:UtilisateurRequest={nom:this.nom.trim(),prenom:this.prenom.trim(),matricule:this.matricule.trim(),telephone:this.telephone.trim()||null,email:this.email.trim(),login:this.login.trim(),motDePasse:this.motDePasse,role:this.role,actif:this.utilisateurSelectionne?.actif??true};const editing=this.modeModification&&this.utilisateurSelectionne;const r=editing?this.api.modifierUtilisateur(this.utilisateurSelectionne!.id,p):this.api.ajouterUtilisateur(p);r.subscribe({next:()=>{this.successMessage=editing?'Utilisateur modifié.':'Utilisateur ajouté.';this.afficherFormulaire=false;this.charger()},error:e=>this.erreur(e,"L'enregistrement a échoué.")})}
 modifierUtilisateur(u:UserView){this.utilisateurSelectionne=u;this.nom=u.nom;this.prenom=u.prenom;this.matricule=u.matricule;this.telephone=u.telephone??'';this.email=u.email;this.login=u.login;this.motDePasse='';this.role=u.role;this.afficherFormulaire=true;this.modeModification=true;this.messageFormulaire=''}supprimerUtilisateur(id:number){this.api.supprimerUtilisateur(id).subscribe({next:()=>this.charger(),error:e=>this.erreur(e,'La désactivation a échoué.')})}
 basculerImport(){this.afficherImport=!this.afficherImport;this.messageImport=''}onDragOver(e:DragEvent){e.preventDefault();this.isDragging=true}onDragLeave(e:DragEvent){e.preventDefault();this.isDragging=false}onDrop(e:DragEvent){e.preventDefault();this.isDragging=false;const f=e.dataTransfer?.files[0];if(f)this.lireFichier(f)}onFileSelected(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)this.lireFichier(f)}private lireFichier(f:File){const r=new FileReader();r.onload=e=>this.traiterCSV(String(e.target?.result??''));r.readAsText(f)}private traiterCSV(c:string){const calls=parseCSV(c).flatMap(row=>{const role=String(row.role??'').toUpperCase() as Role;return ['ADMINISTRATEUR','SUPERVISEUR','NETTOYEUR'].includes(role)?[this.api.ajouterUtilisateur({nom:row.nom??'',prenom:row.prenom??'',matricule:row.matricule??'',telephone:row.telephone||null,email:row.email??'',login:row.login??'',motDePasse:row.motDePasse??'',role,actif:true})]:[]});if(!calls.length){this.messageImport='Aucune ligne CSV valide.';this.typeMessageImport='error';return;}forkJoin(calls).subscribe({next:()=>{this.messageImport=`${calls.length} utilisateur(s) importé(s).`;this.typeMessageImport='success';this.charger()},error:e=>this.erreur(e,"L'import a échoué.")})}private erreur(e:any,f:string){console.error(e);this.messageFormulaire=e?.error?.message||e?.message||f;this.messageImport=this.messageFormulaire;this.typeMessageImport='error'}}
