import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Nettoyage } from '../service/api.models';
import { NettoyageService } from '../service/nettoyage.service';
import { WorkflowNav } from './workflow-nav';
@Component({selector:'app-liste-nettoyages-workflow',standalone:true,imports:[CommonModule,FormsModule,WorkflowNav],styleUrl:'./workflow.css',template:`<app-workflow-nav section="superviseur"/><main class="workflow-page"><div class="workflow-container"><section class="hero-card"><h1>Nettoyages en attente</h1><p>Consultez les demandes qui vous sont affectées.</p></section>@if(error){<div class="error">{{error}}</div>}<section class="panel-card supervisor-filters"><div class="field"><label>Bus</label><select [(ngModel)]="busId" (ngModelChange)="applyFilters()"><option [ngValue]="null">Tous les bus</option>@for(bus of availableBuses;track bus.id){<option [ngValue]="bus.id">Bus {{bus.label}}</option>}</select></div><div class="field"><label>Type de nettoyage</label><select [(ngModel)]="typeId" (ngModelChange)="applyFilters()"><option [ngValue]="null">Tous les types</option>@for(type of availableTypes;track type.id){<option [ngValue]="type.id">{{type.label}}</option>}</select></div></section>@for(n of pagedValues;track n.id){<article class="list-card supervisor-cleaning-card"><div class="assignment-main"><strong>Bus {{n.numeroBus}}</strong><span>{{n.typeNettoyageLibelle}}</span></div><div class="validation-summary"><span><i class="fa-solid fa-user"></i> {{n.nettoyeurNom}}</span><span><i class="fa-regular fa-clock"></i> {{n.duree??0}} min</span></div><span class="badge EN_ATTENTE">En attente</span><button class="secondary-btn" type="button" (click)="ouvrir(n)">Voir détails</button></article>}@empty{<div class="panel-card empty">Aucun nettoyage en attente pour ces filtres.</div>}@if(filteredValues.length>size){<nav class="pagination"><span class="results-count">{{filteredValues.length}} résultat{{filteredValues.length>1?'s':''}}</span><div class="page-buttons"><button (click)="goToPage(page-1)" [disabled]="page===0">Précédent</button>@for(item of pageItems;track $index){@if(item==='…'){<span class="ellipsis">…</span>}@else{<button [class.active]="item===page+1" (click)="goToPage(+item-1)">{{item}}</button>}}<button (click)="goToPage(page+1)" [disabled]="page>=totalPages-1">Suivant</button></div></nav>}</div></main>`})
export class ListeNettoyagesWorkflow implements OnInit,OnDestroy {
  values:Nettoyage[]=[];error='';busId:number|null=null;typeId:number|null=null;page=0;readonly size=5;private synchronisation?:ReturnType<typeof setInterval>;
  constructor(private service:NettoyageService,private router:Router,private cdr:ChangeDetectorRef){}
  ngOnInit():void {this.charger();this.synchronisation=setInterval(()=>this.charger(false),10000);}
  ngOnDestroy():void {if(this.synchronisation)clearInterval(this.synchronisation);}
  private charger(afficherErreur=true):void {this.service.enAttente().subscribe({next:values=>{this.values=values;if(this.busId!==null&&!values.some(value=>value.busId===this.busId))this.busId=null;if(this.typeId!==null&&!values.some(value=>value.typeNettoyageId===this.typeId))this.typeId=null;this.page=Math.min(this.page,Math.max(0,this.totalPages-1));this.error='';this.cdr.detectChanges();},error:error=>{if(afficherErreur)this.error=error?.error?.message||'Impossible de charger les nettoyages.';this.cdr.detectChanges();}})}
  get availableBuses():{id:number;label:string}[]{return [...new Map(this.values.map(value=>[value.busId,{id:value.busId,label:value.numeroBus}])).values()].sort((a,b)=>a.label.localeCompare(b.label,'fr',{numeric:true}));}
  get availableTypes():{id:number;label:string}[]{return [...new Map(this.values.map(value=>[value.typeNettoyageId,{id:value.typeNettoyageId,label:value.typeNettoyageLibelle}])).values()].sort((a,b)=>a.label.localeCompare(b.label,'fr'));}
  get filteredValues():Nettoyage[]{return this.values.filter(value=>(this.busId===null||value.busId===this.busId)&&(this.typeId===null||value.typeNettoyageId===this.typeId));}
  get totalPages():number{return Math.ceil(this.filteredValues.length/this.size);}
  get pagedValues():Nettoyage[]{const start=this.page*this.size;return this.filteredValues.slice(start,start+this.size);}
  get pageItems():(number|string)[]{return compactPages(this.page+1,this.totalPages);}
  applyFilters():void{this.page=0;}
  goToPage(page:number):void{if(page>=0&&page<this.totalPages)this.page=page;}
  ouvrir(value:Nettoyage):void {this.router.navigate(['/superviseur/nettoyages',value.id]);}
}
function compactPages(current:number,total:number):(number|string)[]{const pages=new Set([1,total,current-1,current,current+1]);const valid=[...pages].filter(page=>page>=1&&page<=total).sort((a,b)=>a-b);const result:(number|string)[]=[];valid.forEach((page,index)=>{if(index&&page-valid[index-1]>1)result.push('…');result.push(page);});return result;}
